version: "3"

services: 
    claimsappapi:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./claimsappapi:/claimsappapi
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"